version: '3.1'

services:

  api:
    build:
      context: .
    container_name: api
    networks:
      - totvs-api
    ports: 
      - 8080:8080

  db:
    image: postgres
    restart: always
    container_name: db
    networks:
      - totvs-api
    environment:
      POSTGRES_DB: totvs-api
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432

networks:
  totvs-api:
    driver: bridge           

